### ISSUE TITLE
Voting issue: While Voting the sequence of players are not same.投票画面中船员的显示顺序问题

### ISSUE THREAD

**Issue by nidoze** [NotMyWing/GarrysModAmongUs#89]
While Voting the sequence of players are not same between impostors' view and other players‘ view. hope fix.
投票时，船员的显示顺序在狼人画面中和好人画面中不一样，希望有人会解决。

**Comment by BytewaveMLP** [comment]
This is intentional behavior; when [sorting players to be displayed](https://github.com/NotMyWing/GarrysModAmongUs/blob/bc824f18055c23ac7b363677ba3f7ca221f9c763/src/gamemodes/amongus/gamemode/vgui/vgui_meeting.moon#L800-L809), fellow imposters are given the highest priority, followed by non-imposters, followed by dead players. Imposters will be shown at the top of the list if and only if you are also an imposter, so it shouldn't expose any information you shouldn't already have.

The only thing I could see that would make this an issue is players asking others what order their lists are in. However, those are the kind of metagaming/cheating tactics that are best dealt with as a server moderator, not from a developer's perspective. You could also remove the imposter sort weighting if you really want to, but I don't see it as being a huge issue.

**Comment by nidoze** [comment]
> This is intentional behavior; when [sorting players to be displayed](https://github.com/NotMyWing/GarrysModAmongUs/blob/bc824f18055c23ac7b363677ba3f7ca221f9c763/src/gamemodes/amongus/gamemode/vgui/vgui_meeting.moon#L800-L809), fellow imposters are given the highest priority, followed by non-imposters, followed by dead players. Imposters will be shown at the top of the list if and only if you are also an imposter, so it shouldn't expose any information you shouldn't already have.
> 
> The only thing I could see that would make this an issue is players asking others what order their lists are in. However, those are the kind of metagaming/cheating tactics that are best dealt with as a server moderator, not from a developer's perspective. You could also remove the imposter sort weighting if you really want to, but I don't see it as being a huge issue.

yes, it's truly not a huge issue, of course, we don't ask their position in the list while meeting. But we usually play online using voice chat and we would like to have enough time for each one to discuss, at the expense of that we take turns to discuss clockwise or counterclockwise and no interrupt, so that's why I want the same sort list in everyone's view. Maybe could return a random sort list, but I can't use Lua. Thanks for the reply anyway.

**Comment by NotMyWing** [comment]
Accepting this to keep things consistent and to disallow possible metagaming.
